spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

trc:
  db:
    url: ${TRC_DB_URL}
    username: ${TRC_DB_USERNAME}
    password: ${TRC_DB_PASSWORD}
    driver-class-name: ${TRC_DB_DRIVER_CLASS_NAME}
  auth:
    jwt:
      secret: ${TRC_JWT_SECRET}
      expiration-time: ${TRC_JWT_EXPIRATION_TIME}