spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  application:
    name: ms-terracota-user

  jpa:
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /ms-user/

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    br.com.terracota: INFO
